### ISSUE TITLE
Doors open weirdly

### ISSUE THREAD

**Issue by VanessaE** [ac-minetest/skyblock#4]
Consider a steel door with its latch on the left, hinges on the right.  Open it, and the door should flip to the right side of the node it's in, keeping the hinges on the right, closest to the player.  Nope.  This happens:

![image](https://user-images.githubusercontent.com/1733537/47599726-e58c8400-d981-11e8-936f-faca56e476e7.png)

Notice how the hinges switch sides.  The node's being rotated wrong, placing it on the wrong side of it's node space.

Works fine in plain minetest_game, or with e.g. Dreambuilder.

**Comment by ac-minetest** [comment]
minetest doors change with every minor version change (0.4.16->0.4.16.1->...) When opening door relevant
"on_rightclick" thing is called, its annoying to change every minor version since there is no 'standard' open door...
